FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY client.js /usr/share/nginx/html/
COPY CHANGELOG.md /usr/share/nginx/html/
COPY sprites/ /usr/share/nginx/html/sprites/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
